image: python:3.9

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - pip install -r requirements.txt
    - python app.py

deploy:
  stage: deploy
  script:
    - pip install gunicorn
    - gunicorn -b 0.0.0.0:$PORT app:app
  environment: production